version: '3.8'

services:
  postgres:
    container_name: calc_v33
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - my_db_v33_data:/var/lib/postgresql/data
    command: postgres -N 500

  redis:
    container_name: calc_v33_redis
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - my_db_data_v33_redis:/data
    networks:
      - calc_v33

volumes:
  my_db_v33_data:
    driver: local
  my_db_data_v33_redis:
    driver: local

networks:
  calc_v33:
    driver: bridge
