version: '3.8'

services:
  postgres:
    container_name: calc_v2
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - my_db_v2_data:/var/lib/postgresql/data
    command: postgres -N 500

  redis:
    container_name: calc_v2_redis
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - my_db_data_v2_redis:/data
    networks:
      - code_film

volumes:
  my_db_v2_data:
    driver: local
  my_db_data_v2_redis:
    driver: local

networks:
  calc_v2:
    driver: bridge
