"""addprice_for_electricity_to_user

Revision ID: 7cb4a66d2fb5
Revises: 790b4d7014cd
Create Date: 2024-02-18 16:57:29.930369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb4a66d2fb5'
down_revision: Union[str, None] = '790b4d7014cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('price_for_electricity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'price_for_electricity')
    # ### end Alembic commands ###
