"""add_alg_to_product

Revision ID: ec3f4538327f
Revises: 7cb4a66d2fb5
Create Date: 2024-02-20 05:43:09.395705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3f4538327f'
down_revision: Union[str, None] = '7cb4a66d2fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('algorithm', sa.String(), nullable=True))
    op.execute("UPDATE products SET algorithm = 'sha256'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'algorithm')
    # ### end Alembic commands ###
